pod2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')), # modifique esta linha
    path('post/', include('post.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]

post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('', views.PostListView.as_view(), name='index'),
    path('update/<int:post_id>/', views.update_post, name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

post/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    conteudo = models.CharField(max_length=400)
    data_postagem = models.DateTimeField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.release_year})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    data_postagem = models.DateTimeField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

    class Meta:
       ordering = ('-data_postagem',)

post/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'release_year',
            'conteudo',
            'data_postagem',
            'poster_url',
        ]
        labels = {
            'name': 'Título',
            'release_year': 'Data de Lançamento',
            'conteudo': 'Conteudo da Postagem',
            'data_postagem': 'Data da Postagem',
            'poster_url': 'URL do Poster',
        }
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
            'data_postagem'
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
            'data_postagem':'Data'
        }

post/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .temp_data import post_data
from django.urls import reverse, reverse_lazy
from .models import Post, Comment
from django.views import generic
from .forms import PostForm, CommentForm
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView


class PostListView(generic.ListView):
   post = Post
   template_name = 'post/index.html'


   def get_queryset(self):
       return Post.objects.order_by('id')


class PostDetailView(generic.DetailView):
   post = Post
   template_name = 'post/detail.html'


   def get_queryset(self):
       return Post.objects.all()


class PostCreateView(CreateView):
   form_class = PostForm
   template_name = 'post/create.html'
   success_url = reverse_lazy('post:index')


   def form_valid(self, form):
       return super().form_valid(form)


class PostUpdateView(UpdateView):
   form_class = PostForm
   template_name = 'post/update.html'
   success_url = reverse_lazy('post:index')


   def form_valid(self, form):
       return super().form_valid(form)


   def get_queryset(self):
       return Post.objects.all()


class PostDeleteView(DeleteView):
   model = Post
   success_url = reverse_lazy('post:index')
   template_name = 'post/delete.html'


   def get_object(self, queryset=None):
     post_id = self.request.POST.get('pk')
     return self.get_queryset().filter(pk=post_id).get()


def list_post(request):
    context = {"post_list": post_data}
    return render(request, 'post/index.html', context)


def detail_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'post/detail.html', context)


def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_name = form.cleaned_data['name']
            post_release_year = form.cleaned_data['release_year']
            post_conteudo = form.cleaned_data['conteudo']
            post_data_postagem = form.cleaned_data['data_postagem']
            post_poster_url = form.cleaned_data['poster_url']
            post = Post(name=post_name,
                          release_year=post_release_year, conteudo = post_conteudo,
                          data_postagem = post_data_postagem, poster_url=post_poster_url)
            post.save()
            return HttpResponseRedirect(
                reverse('post:detail', args=(post.id, )))
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'post/create.html', context)


def update_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post.name = form.cleaned_data['name']
            post.release_year = form.cleaned_data['release_year']
            post_conteudo = form.cleaned_data['conteudo']
            post_data_postagem = form.cleaned_data['data_postagem']
            post.poster_url = form.cleaned_data['poster_url']
            post.save()
            return HttpResponseRedirect(
                reverse('post:detail', args=(post.id, )))
    else:
        form = PostForm(
            initial={
                'name': post.name,
                'release_year': post.release_year,
                'conteudo' : post.conteudo,
                'data_postagem' : post.data_postagem,
                'poster_url': post.poster_url
            })
    context = {'post': post, 'form': form}
    return render(request, 'post/update.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('post:index'))
    context = {'post': post}
    return render(request, 'post/delete.html', context)
    
def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment_data_postagem= form.cleaned_data['data_postagem']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            data_postagem=comment_data_postagem,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('post:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'post/comment.html', context)

staticpages/views.py
# Create your views here.
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

post/templates/post/comment.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <section class="form">
        <h2>Criar um comentário</h2>
        <form method="POST" action="{% url 'post:comment' post.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Postar</button>
        </form>
        <a class="button voltar" href="{% url 'post:detail' post.id %}" >Voltar</a>
    </section>
    
</div>

{% endblock content %}

post/templates/post/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Podcast</h2>
<form method="post" action="{% url 'post:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

post/templates/post/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'post:delete' post.id %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja apagar o Post?
  </p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

post/templates/post/detail.html
{% extends 'base.html' %} 
{% block title %} 
{{ post.name }} {{ post.release_year }} 
{% endblock title %} 
{% block content %}

    <div class = "container">   
    <section class="lista-de-posts">
        <h2>Detalhes do Podcast </h2> 
        <img src="{{ post.poster_url }}" alt="Poster do filme {{ post.name}}" />
        <ul>
            <li>Nome: {{ post.name }}</li>
            <li>Ano de Lançamento: {{ post.release_year }}</li>
            <li>Conteúdo do Post: </li>
            <p>{{post.conteudo}}</p>
            <li>Data de Postagem:</li>
            <p>{{post.data_postagem}}</p>
            <section>
                <h2>Comentários</h2>
                <ul>
                    {% if post.comment_set.all %}
                        {% for comment in post.comment_set.all %}
                            <section class="comment">
                                <p> "{{ comment.text }}" </p>
                                <p> <i>Autor: </i>{{ comment.author }}</p>
                                <p><i>Postado em: </i> {{ comment.data_postagem }}</p>
                            </section>
                        {% endfor %}
                    {% else %}
                        <p><i>Não há comentários para este post.</i></p>
                    {% endif %}
                </ul>
            
                {% if post.category_set.all %}
                <p>Categorias deste post: {{ post.category_set.all|join:", " }} </p>
                {% endif %}
            </section>        
    
            <li><a href="{% url 'post:update' post.id %}">Editar</a></li>
            <li><a href="{% url 'post:delete' post.id %}">Apagar</a></li>
            <a class="button voltar" href="{% url 'post:comment' post.id %}" >Postar um comentário</a>
        </ul>
    </section>
    </div>
    {% endblock content %}

post/templates/post/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <section class="lista-de-posts">
        <h2>Todos os Podcasts</h2>

    {% if post_list %}

        {% for post in post_list %}
        <article class="post">
            <a href="{% url 'post:detail' post.id %}"> <!-- modifique esta linha -->
            <a href="{% url 'post:detail' forloop.counter %}">
            <img src="{{ post.poster_url }}" alt="Poster do filme {{ post.name}}"/></a>
            <p>{{ post.name }} {{post.conteudo}} {{post.data_postagem}} ({{ post.release_year }})</p>
        </article>
        {% endfor %}
        <p class="lista-de-posts">
            Não encontrou o podcast?
            <a href="{% url 'post:create' %}">Adicionar Novo Post</a>
          </p>
    </section>
    {% else %}
        <p>Não foi encontrado nenhum filme.</p>
</div>
    {% endif %}
{% endblock content %}

post/templates/post/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Podcast{{ post.name }} {{post.conteudo}} {{post.data_postagem}} ({{ post.release_year}})</h2>
<form method="POST" action="{% url 'post:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | PODIVERSOS!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha --> <!--add a pasta static-->
</head>

<body>
    <header>
        <a href="{% url 'index' %}"> <img src="{% static 'pod03.png' %}"alt="logo" width="64" height="64"> </a> <!-- adicione esta linha -->
        <nav>
            <div class="navigation-box">
                <a href="{% url 'index' %}" class="button">Home</a>    
            </div>
            <div class="navigation-box">
                <a href="{% url 'about' %}" class="button">Sobre</a>
            </div>
    
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2023 Guzzi.</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
SOBRE
{% endblock title %}

{% block content %}
<div class="container" >
    <section>
        <h2>Sobre o Podiversos</h2>
        <div class = "content-item">
        <p> O blog Podiverso nasceu da ideia de compartilhar a ideia de conhecer, ouvir e gostar de podcasts.
            Aqui serão listados podcasts que sempre buscam proporcionar ao ouvinte conhecimento, seja ele científico, educacional, esportivo e cultural.</p>
        <p> Você que se interessa também em ouvir podcasts e quer mostrar sua resenha de algum específico, junte-se com a gente! Vamos dissiminar 
            informações pelo mundo
        </p>
        
        <h2>O que é um Podcast?</h2>
        <p>
            Um podcast é uma forma de mídia digital que consiste em uma série de episódios de áudio ou vídeo, geralmente focada em um tópico 
            específico ou tema. Os podcasts podem ser ouvidos ou assistidos online e geralmente são disponibilizados em plataformas de streaming ou download. 
            Eles oferecem uma maneira conveniente para os ouvintes acessarem conteúdo sob demanda, como discussões, entrevistas, histórias ou informações sobre 
            uma variedade de assuntos, desde notícias e entretenimento até educação e hobbies. Os ouvintes podem se inscrever em podcasts
             
            para receber automaticamente novos episódios quando são lançados, tornando-os uma forma popular de consumo de conteúdo multimídia.
        </p>
        </div>
    </section>
</div>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<div class = "container">
    <section>
        <div class="content-item home">
            <h1><i>PODIVERSOS</i></h1>
            <h2>E porquê compartilhar podcasts?</h2>
            <p>Bem vindo ao <i>PODIVERSOS</i>, o site destinado a compartilhar com o mundo um pouquinho sobre <b>podcasts</b>!
                Neste site, você encontrará:</p>
            <ul>
                <li> Uma explicação sobre a motivação do site </li>
                <li>Uma contextualização sobre a história dos podcasts</li>
                <li>Um pouco sobre os primeiros podcasts que surgiram no Brasil</li>
            </ul>
            <h2>Os podcasts ao longo da História</h2>
            <h3>Motivação do podiversos</h3>
            <p>O blog Podiverso nasceu da ideia de compartilhar a ideia de conhecer, ouvir e gostar de podcasts. 
                Aqui serão listados podcasts que sempre buscam proporcionar ao ouvinte conhecimento, seja ele científico,
                 educacional, esportivo e cultural.
                Você que se interessa também em ouvir podcasts e quer mostrar sua resenha de algum específico, 
                junte-se com a gente! Vamos dissiminar informações pelo mundo.</p>
            <h3>Sobre os podcasts</h3>
            <p>Podcasts são programas de áudio, geralmente em formato de episódios, que podem abordar uma ampla variedade de temas, 
                como notícias, entretenimento, educação, entrevistas, e muito mais. Eles são disponibilizados online para streaming ou download 
                e podem ser ouvidos em dispositivos como smartphones, tablets e computadores. A palavra "podcast" é uma combinação de "iPod", o
                 popular dispositivo da Apple, e "broadcast" (transmissão, em inglês), refletindo a facilidade com que esses programas podem ser 
                 consumidos sob demanda. Os podcasts oferecem uma forma conveniente de aprender, se entreter e se manter atualizado sobre diversos 
                 assuntos, e são populares em todo o mundo.</p>
            <h3>Primeiros podcasts que surgiram no Brasil</h3>
            <p>Identificar os primeiros podcasts específicos no Brasil pode ser desafiador devido à falta de registros precisos, 
                mas alguns dos pioneiros incluem:

                <li>Digital Minds: Um dos primeiros podcasts brasileiros, lançado em 2004, focado em tecnologia e inovação.</li>
                
                <li>Nerdcast: Iniciado em 2006, é um dos podcasts mais populares do Brasil. Produzido pelo site Jovem Nerd, aborda temas geek, 
                    cultura pop, e diversos assuntos. </li>
                
                <li> Guia Prático: Criado por Rodrigo Ghedin e Ronaldo Prass em 2007, abordava temas relacionados à tecnologia e internet.</li>
                
                Esses podcasts foram alguns dos primeiros a explorar o formato no Brasil e contribuíram para a popularização do meio no país. 
                Vale ressaltar que o cenário dos podcasts evoluiu significativamente desde então, com uma grande variedade de programas disponíveis 
                em diversas categorias.</p>
            <h3>Dias atuais</h3>
            <p>Atualmente, os podcasts estão em alta, com uma explosão de conteúdo que abrange uma variedade de temas. 
                Empresas, celebridades e criadores independentes contribuem para a diversidade do formato. A monetização, 
                através de anúncios e assinaturas, se tornou comum, e as plataformas de streaming desempenham um papel fundamental 
                na distribuição. Além disso, podcasts cultivam comunidades ativas e transcenderam fronteiras, proporcionando uma experiência 
                global de consumo de conteúdo em áudio.</p>
        </div>
    </section>

    <aside class="home">
        <img src="{% static 'pod01.png' %}"  alt="paw trail" width="auto" height="50%">
    </aside>
    
</div>
{% endblock content %}

templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | PODIVERSOS!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha --> <!--add a pasta static-->
</head>

<body>
    <header>
        <a href="{% url 'index' %}"> <img src="{% static 'pod03.png' %}"alt="logo" width="64" height="64"> </a> <!-- adicione esta linha -->
        <nav>
            <div class="navigation-box">
                <a href="{% url 'index' %}" class="button">Home</a>    
            </div>
            <div class="navigation-box">
                <a href="{% url 'about' %}" class="button">Sobre</a>
            </div>
            <div class="navigation-box">
                <a href="{% url 'post:index' %}">Blog</a>
            </div>
    
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2023 Guzzi.</small>
        </p>
    </footer>
</body>

</html>